"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase";

type Profile = { display_name: string | null; phone_verified_at: string | null; country_code: string | null };
type Account = { id: string; currency: string; available_minor: string; held_minor: string; committed_minor: string };

export default function DashboardPage() {
  const router = useRouter();
  const [ready, setReady] = useState(false);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const supabase=createClient(); let active=true; const load=async()=>{const{data:auth}=await supabase.auth.getUser();if(!active)return;if(!auth.user){router.replace("/auth");return;}const[{data:p},{data:a,error:ae}]=await Promise.all([supabase.from("money_profiles").select("display_name,phone_verified_at,country_code").eq("user_id",auth.user.id).maybeSingle(),supabase.from("money_accounts").select("id,currency,available_minor,held_minor,committed_minor").eq("owner_id",auth.user.id).order("created_at",{ascending:true})]);if(ae)setError(ae.message);if(active){setProfile(p);setAccounts((a??[]) as Account[]);setReady(true)}};void load();const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(!session)router.replace("/auth")});return()=>{active=false;listener.subscription.unsubscribe()}},[router]);
  if(!ready)return <main className="shell auth-shell"><section className="auth-card"><p className="eyebrow">SHADECODE · MONEY</p><h1>Loading your workspace…</h1><p className="subhead">Checking identity, wallet and money services.</p></section></main>;
  const available=accounts.reduce((sum,a)=>sum+Number(a.available_minor),0)/100; const held=accounts.reduce((sum,a)=>sum+Number(a.held_minor),0)/100;
  return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode Money</span></div><div className="nav-actions"><a href="/send">Send</a><a href="/plans">Plans</a><a href="/account">Account</a></div></nav><section className="hero"><p className="eyebrow">SHADECODE · MONEY</p><h1>{profile?.display_name?`Welcome, ${profile.display_name}.`:"Your money workspace."}</h1><p className="subhead">Manage your balance, send money, review transactions and manage your account.</p></section>{error&&<p className="session-message" role="status">{error}</p>}{!profile?.phone_verified_at&&<section className="preview"><div><p className="label">ACCOUNT SETUP</p><h2>Verify your phone to use money features.</h2><p className="request">Phone verification is required before your number can be used as a trusted money identifier or recipient lookup target.</p></div><a className="link-button" href="/account">Verify phone →</a></section>}<section className="preview-grid workspace-grid"><a className="preview tile" href="/wallet"><p className="label">WALLET</p><h2>{accounts.length} account{accounts.length===1?"":"s"}</h2><p>Available {available.toFixed(2)} · Held {held.toFixed(2)}</p><strong>Open wallet →</strong></a><a className="preview tile" href="/send"><p className="label">SEND</p><h2>Send money</h2><p>Find a verified recipient, review the cost and authorize a transfer.</p><strong>Send money →</strong></a><a className="preview tile" href="/plans"><p className="label">PLANS</p><h2>Money plans</h2><p>Manage routes, holds, schedules, splits and goals.</p><strong>Open plans →</strong></a><a className="preview tile" href="/transactions"><p className="label">TRANSACTIONS</p><h2>Transaction history</h2><p>Review your money movements and settlement states.</p><strong>View transactions →</strong></a><a className="preview tile" href="/account"><p className="label">ACCOUNT</p><h2>Account & phone</h2><p>Manage your name, country and verified phone number.</p><strong>Manage account →</strong></a></section><section className="principles"><article><b>01</b><h3>Choose</h3><p>Tell Money what you want to do.</p></article><article><b>02</b><h3>Review</h3><p>See the available option, cost and timing.</p></article><article><b>03</b><h3>Confirm</h3><p>Verify the details before money moves.</p></article></section><footer>Shadecode Money · Your money, your controls</footer></main>;
}
