"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase";

type Plan={id:string;kind:string;status:string;title:string;intent:Record<string,unknown>;plan:Record<string,unknown>;created_at:string};
const kinds=[
  ["ROUTE","Route a payment"],["HOLD","Hold money"],["SCHEDULE","Schedule a payment"],["SPLIT","Split a payment"],["GOAL","Create a money goal"]
] as const;

export default function PlansPage(){
 const router=useRouter(); const [plans,setPlans]=useState<Plan[]>([]); const [kind,setKind]=useState("ROUTE"); const [title,setTitle]=useState(""); const [intent,setIntent]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 useEffect(()=>{const sb=createClient();let live=true;void(async()=>{const{data:a}=await sb.auth.getUser();if(!a.user){router.replace("/auth");return;}const{data,error}=await sb.from("money_plans").select("id,kind,status,title,intent,plan,created_at").order("created_at",{ascending:false});if(live){if(error)setMessage(error.message);setPlans((data??[]) as Plan[]);}})();return()=>{live=false}},[router]);
 async function createPlan(e:FormEvent){e.preventDefault();setBusy(true);setMessage(null);const sb=createClient();const{data:a}=await sb.auth.getUser();if(!a.user){router.replace("/auth");return;}let parsed:Record<string,unknown>={};if(intent.trim()){try{parsed=JSON.parse(intent)}catch{setMessage("Intent must be valid JSON, or leave it blank.");setBusy(false);return;}}const{data,error}=await sb.rpc("create_money_plan",{p_kind:kind,p_title:title.trim()||kinds.find(x=>x[0]===kind)?.[1]||kind,p_intent:parsed,p_plan:{source:"navigator"}});setBusy(false);if(error){setMessage(error.message);return;}setPlans(p=>[data as Plan,...p]);setTitle("");setIntent("");setMessage("Plan saved. It is ready for the next execution workflow.")}
 return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode Money</span></div><div className="nav-actions"><a href="/dashboard">Workspace</a><a href="/account">Account</a></div></nav><section className="hero"><p className="eyebrow">SHADECODE · MONEY PLANS</p><h1>Turn intent into a plan.</h1><p className="subhead">Save routes, holds, recurring payments, splits and goals now. Execution remains simulation-only until the live rails are enabled.</p></section><section className="preview"><form onSubmit={createPlan}><label>Plan type<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Rent every month"/></label><label>Intent JSON <span className="label">optional</span><textarea value={intent} onChange={e=>setIntent(e.target.value)} placeholder={'{"amount_minor":5000,"currency":"USD"}'}/></label><button disabled={busy}>{busy?"Saving…":"Save plan"}</button></form>{message&&<p className="session-message" role="status">{message}</p>}</section><section className="preview-grid">{plans.length===0?<article className="preview"><p className="label">PLANS</p><h2>No saved plans yet.</h2><p>Build the first plan above.</p></article>:plans.map(p=><article className="preview tile" key={p.id}><p className="label">{p.kind} · {p.status}</p><h2>{p.title}</h2><p>Created {new Date(p.created_at).toLocaleString()}</p><strong>{p.status==="READY"?"Ready for execution":"Track plan →"}</strong></article>)}</section><footer>Shadecode Money · Navigator · Plans · M0.1 · No real-money execution</footer></main>}
