"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase";

type Profile={user_id:string;username:string|null;display_name:string|null;phone_e164:string|null;phone_verified_at:string|null;country_code:string|null;email_verified_at:string|null};
const normalizePhone=(value:string,country="ZW")=>{const v=value.trim().replace(/[\s()-]/g,"");if(/^\+[1-9][0-9]{6,14}$/.test(v))return v;if(country==="ZW"&&/^0[0-9]{8,9}$/.test(v))return `+263${v.slice(1)}`;return v};
const E164=/^\+[1-9][0-9]{6,14}$/; const USERNAME=/^[A-Za-z0-9_]{3,32}$/;
export default function AccountPage(){const router=useRouter();const[profile,setProfile]=useState<Profile|null>(null);const[username,setUsername]=useState("");const[displayName,setDisplayName]=useState("");const[phone,setPhone]=useState("");const[country,setCountry]=useState("ZW");const[otp,setOtp]=useState("");const[challengeId,setChallengeId]=useState("");const[simulatedCode,setSimulatedCode]=useState("");const[otpSent,setOtpSent]=useState(false);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(true);const[saving,setSaving]=useState(false);const[verifying,setVerifying]=useState(false);
useEffect(()=>{const sb=createClient();void(async()=>{const{data:auth}=await sb.auth.getUser();if(!auth.user){router.replace("/auth");return;}const{data,error}=await sb.from("money_profiles").select("user_id,username,display_name,phone_e164,phone_verified_at,country_code,email_verified_at").eq("user_id",auth.user.id).maybeSingle();if(error)setMessage(error.message);if(data){setProfile(data);setUsername(data.username??"");setDisplayName(data.display_name??"");setPhone(data.phone_e164??"");setCountry(data.country_code??"ZW");}setBusy(false);})();const{data:listener}=sb.auth.onAuthStateChange((_e,s)=>{if(!s)router.replace("/auth")});return()=>listener.subscription.unsubscribe()},[router]);
async function signOut(){await createClient().auth.signOut();router.replace("/auth")}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage(null);const sb=createClient();const{data:auth}=await sb.auth.getUser();if(!auth.user){router.replace("/auth");return;}const normalized=normalizePhone(phone,country);if(!USERNAME.test(username.trim())){setMessage("Username must be 3–32 characters using letters, numbers or underscores.");setSaving(false);return;}if(!E164.test(normalized)){setMessage("Enter a valid phone number, for example 0771234567 or +263771234567.");setSaving(false);return;}const{data,error}=await sb.from("money_profiles").upsert({user_id:auth.user.id,username:username.trim(),display_name:displayName.trim()||null,phone_e164:normalized,country_code:country.trim().toUpperCase()||null},{onConflict:"user_id"}).select("user_id,username,display_name,phone_e164,phone_verified_at,country_code,email_verified_at").single();setSaving(false);if(error){setMessage(error.code==="23505"?"That username or phone number is already in use.":error.message);return;}setProfile(data);setPhone(normalized);setMessage("Account information saved. Verify the phone number before using it for money transfers.");}
async function sendOtp(){const normalized=normalizePhone(phone,country);if(!E164.test(normalized)){setMessage("Enter a valid phone number, for example 0771234567 or +263771234567.");return;}setPhone(normalized);setVerifying(true);setMessage(null);setSimulatedCode("");const{data,error}=await createClient().functions.invoke("money-phone-otp-v3",{body:{action:"start",phoneE164:normalized}});setVerifying(false);if(error||!data?.challengeId){setMessage(error?.message??data?.error??"Phone verification service unavailable.");return;}setChallengeId(String(data.challengeId));setOtpSent(true);if(data.deliveryMode==="SIMULATED")setSimulatedCode(String(data.simulatedCode??""));setMessage(data.deliveryMode==="SIMULATED"?"Simulator mode: use the code shown below. No SMS is sent in M0.1.":"Verification code sent by SMS.")}
async function verifyOtp(){const normalized=normalizePhone(phone,country);if(!challengeId||!E164.test(normalized)||!/^[0-9]{6}$/.test(otp)){setMessage("Enter the 6-digit verification code.");return;}setVerifying(true);setMessage(null);const{data,error}=await createClient().functions.invoke("money-phone-otp-v3",{body:{action:"verify",phoneE164:normalized,challengeId,otp}});setVerifying(false);if(error||!data?.verified){setMessage(error?.message??data?.error??"Phone verification failed.");return;}const{data:auth}=await createClient().auth.getUser();if(auth.user){const{data:refreshed}=await createClient().from("money_profiles").select("user_id,username,display_name,phone_e164,phone_verified_at,country_code,email_verified_at").eq("user_id",auth.user.id).single();if(refreshed)setProfile(refreshed)}setOtpSent(false);setChallengeId("");setOtp("");setSimulatedCode("");setMessage("Phone verified successfully. This number is now a trusted Money identifier.")}
if(busy)return <main className="shell auth-shell"><section className="auth-card"><p className="eyebrow">SHADECODE · MONEY</p><h1>Loading your account…</h1></section></main>;
return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode Money</span></div><div className="nav-actions"><a href="/dashboard">Workspace</a><button className="link-button" type="button" onClick={signOut}>Sign out</button></div></nav><section className="auth-card"><p className="eyebrow">SHADECODE · IDENTITY</p><h1>Your account.</h1><p className="subhead">Your username and profile information are stored in Money. A phone number becomes a trusted identifier only after verification.</p><form onSubmit={save}><label>Username<input autoComplete="username" placeholder="e.g. takunda_01" value={username} onChange={e=>setUsername(e.target.value.replace(/\s/g,""))}/></label><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>Phone number<input inputMode="tel" autoComplete="tel" placeholder="0771234567 or +263771234567" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Country code<input maxLength={2} placeholder="ZW" value={country} onChange={e=>setCountry(e.target.value.toUpperCase())}/></label><button type="submit" disabled={saving}>{saving?"Saving…":"Save account information"}</button></form>{profile?.phone_verified_at?<div className="session-message">✓ Phone verified · {profile.phone_e164}</div>:<div><div className="session-message">○ Phone not verified</div><button type="button" onClick={sendOtp} disabled={verifying||!phone}>{verifying?"Creating challenge…":"Send verification code"}</button>{otpSent&&<div>{simulatedCode&&<div className="session-message"><strong>SIMULATED SMS CODE: {simulatedCode}</strong><br/>M0.1 simulator only. Real SMS delivery can be enabled later.</div>}<label>6-digit code<input inputMode="numeric" maxLength={6} autoComplete="one-time-code" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))}/></label><button type="button" onClick={verifyOtp} disabled={verifying||otp.length!==6}>{verifying?"Verifying…":"Verify phone"}</button></div>}</div>}{message&&<p className="session-message" role="status">{message}</p>}</section></main>}
