"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase";

type Account = { id: string; currency: string; available_minor: string; held_minor: string; committed_minor: string; account_mode: "LIVE" | "SIMULATOR" };
const money = (minor: string) => (Number(minor) / 100).toFixed(2);

export default function WalletPage() {
  const router = useRouter();
  const [accounts, setAccounts] = useState<Account[]>([]); const [email, setEmail] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [funding, setFunding] = useState<{id:string;currency:string}|null>(null); const [fundAmount, setFundAmount] = useState("20"); const [fundBusy, setFundBusy] = useState(false);
  async function load(){const supabase=createClient();const{data:auth,error:ae}=await supabase.auth.getUser();if(!auth.user){router.replace("/auth");return;}if(ae){setMessage(ae.message);setBusy(false);return;}setEmail(auth.user.email??"");const{data,error}=await supabase.from("money_accounts").select("id,currency,available_minor,held_minor,committed_minor,account_mode").eq("owner_id",auth.user.id).order("created_at",{ascending:true});if(error)setMessage(error.message);else setAccounts((data??[]) as Account[]);setBusy(false)}
  useEffect(()=>{void load()},[router]);
  async function startFunding(){if(!funding)return;const amount=Number(fundAmount);if(!Number.isFinite(amount)||amount<=0){setMessage("Enter a positive funding amount.");return;}setFundBusy(true);setMessage(null);try{const response=await fetch("/api/providers/paynow/fund",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:funding.id,currency:funding.currency,amount})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to start funding");window.location.assign(data.browserUrl)}catch(error){setMessage(error instanceof Error?error.message:"Funding failed");setFundBusy(false)}}
  return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode Money</span></div><div className="nav-actions"><a href="/dashboard">Workspace</a><a href="/account">Account</a></div></nav><section className="hero"><p className="eyebrow">SHADECODE · LIVE WALLET</p><h1>Your money, clearly.</h1><p className="subhead">{email}</p></section>{busy?<p>Loading accounts…</p>:message&&!accounts.length?<p className="session-message" role="status">{message}</p>:<><section className="wallet-grid">{accounts.length===0?<article className="preview"><p className="label">GET STARTED</p><h2>Open your first live wallet.</h2><p>Live accounts require verified identity before real funds can be accepted.</p><a className="link-button" href="/wallet/create">Open live account →</a></article>:accounts.map(a=><article className="preview" key={a.id}><p className="label">{a.account_mode} · {a.currency}</p><h2>{money(a.available_minor)} {a.currency}</h2><div className="preview-grid"><div><span>Available</span><strong>{money(a.available_minor)} {a.currency}</strong></div><div><span>Held</span><strong>{money(a.held_minor)} {a.currency}</strong></div><div><span>Committed</span><strong>{money(a.committed_minor)} {a.currency}</strong></div></div>{a.account_mode==="LIVE"&&<button onClick={()=>{setFunding({id:a.id,currency:a.currency});setFundAmount("20")}}>Add real money</button>}</article>)}</section>{message&&<p className="session-message" role="status">{message}</p>}<p><a className="link-button" href="/wallet/create">+ Add live currency</a> · <a className="link-button" href="/transactions">View ledger</a></p></>}{funding&&<div className="auth-shell" role="dialog" aria-modal="true"><section className="auth-card"><p className="eyebrow">PAYNOW · FUND WALLET</p><h2>Add {funding.currency}.</h2><p className="subhead">You will be redirected to Paynow to complete the payment. Your wallet is credited only after a verified provider notification.</p><label>Amount<input inputMode="decimal" value={fundAmount} onChange={e=>setFundAmount(e.target.value)}/></label><button onClick={startFunding} disabled={fundBusy}>{fundBusy?"Opening Paynow…":"Continue to Paynow"}</button><button className="link-button" onClick={()=>setFunding(null)}>Cancel</button></section></div>}<footer>Shadecode Money · Live wallet</footer></main>;
}
