"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase";
import { getRouteQuote, type RouteQuote } from "./quote";

type Recipient = { user_id: string; display_name: string | null; country_code: string | null };
const normalizePhone=(v:string)=>v.trim().replace(/[\s()-]/g,""); const nonce=()=>`${crypto.randomUUID()}-${Date.now()}`;
export default function SendPage(){const router=useRouter();const[ready,setReady]=useState(false);const[phone,setPhone]=useState("");const[amount,setAmount]=useState("");const[currency,setCurrency]=useState("USD");const[recipient,setRecipient]=useState<Recipient|null>(null);const[routes,setRoutes]=useState<RouteQuote[]>([]);const[selectedRoute,setSelectedRoute]=useState<RouteQuote|null>(null);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);useEffect(()=>{const sb=createClient();let active=true;void sb.auth.getUser().then(({data})=>{if(!active)return;if(!data.user)router.replace("/auth");else setReady(true)});return()=>{active=false}},[router]);
async function findRecipient(){setBusy(true);setMessage(null);setRecipient(null);setRoutes([]);setSelectedRoute(null);setAuthorized(false);const p=normalizePhone(phone);if(!/^\+[1-9][0-9]{6,14}$/.test(p)){setMessage("Enter a valid international phone number, for example +263771234567.");setBusy(false);return;}const{data,error}=await createClient().rpc("lookup_money_recipient_by_phone",{p_phone_e164:p});setBusy(false);if(error){setMessage(error.message);return;}const match=Array.isArray(data)?data[0]:data;if(!match){setMessage("No verified recipient found. The recipient must have a verified Shadecode Money phone number and must be a different user.");return;}setRecipient(match as Recipient)}
async function quote(){setMessage(null);setRoutes([]);setSelectedRoute(null);setAuthorized(false);const n=Number(amount);if(!recipient)return setMessage("Find and review the recipient first.");if(!Number.isFinite(n)||n<=0)return setMessage("Enter a valid positive amount.");setBusy(true);try{const result=await getRouteQuote(n,currency,recipient.country_code??"");setRoutes(result.routes);if(!result.routes.length)setMessage("No eligible money rail is configured for this currency.")}catch(e){setMessage(e instanceof Error?e.message:"Route quote failed.")}finally{setBusy(false)}}
async function authorize(){if(!recipient||!selectedRoute)return;setBusy(true);setMessage(null);try{const sb=createClient();const{data:auth}=await sb.auth.getUser();if(!auth.user){router.replace("/auth");return;}const{data:accounts,error}=await sb.from("money_accounts").select("id,currency").eq("owner_id",auth.user.id).eq("currency",currency).order("created_at",{ascending:true}).limit(1);if(error)throw error;const account=accounts?.[0];if(!account){setMessage(`No ${currency} account is available. Create one in Wallet first.`);return;}const{data,error:fnError}=await sb.functions.invoke("money-authorize-transfer-v3",{body:{accountId:account.id,currency,amountMinor:Math.round(Number(amount)*100),recipientPhone:normalizePhone(phone),idempotencyKey:nonce()}});if(fnError)throw fnError;if(data?.error)throw new Error(data.error);setAuthorized(true)}catch(e){setMessage(e instanceof Error?e.message:"Transfer authorization failed")}finally{setBusy(false)}}
if(!ready)return <main className="shell auth-shell"><section className="auth-card"><p className="eyebrow">SHADECODE · MONEY</p><h1>Loading transfer workspace…</h1><p className="subhead">Checking your signed-in session.</p></section></main>;
return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode Money</span></div><div className="nav-actions"><a href="/dashboard">Workspace</a><a href="/wallet">Wallet</a></div></nav><section className="hero"><p className="eyebrow">SHADECODE · SEND</p><h1>Prepare a transfer.</h1><p className="subhead">Recipient, route, balance and authorization are checked before settlement can begin.</p></section><section className="preview"><p className="label">01 · RECIPIENT</p><div className="recipient-form"><input inputMode="tel" placeholder="Recipient +263771234567" value={phone} onChange={e=>setPhone(e.target.value)}/><button onClick={findRecipient} disabled={busy}>{busy?"Looking up…":"Find recipient"}</button></div>{recipient&&<div className="recipient-result"><strong>{recipient.display_name??"Shadecode Money user"}</strong><span>{recipient.country_code??""}</span><p>Verified recipient identity found.</p></div>}</section><section className="preview"><p className="label">02 · AMOUNT</p><div className="recipient-form"><input inputMode="decimal" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>ZWL</option><option>ZAR</option><option>GBP</option><option>EUR</option></select></div><button onClick={quote} disabled={!recipient||!amount||busy}>{busy?"Quoting…":"Get route options"}</button></section>{routes.length>0&&<section className="preview"><p className="label">03 · ROUTE</p><h2>Choose an eligible route.</h2><div className="route-list">{routes.map(route=><button className="transaction-row" key={route.id} disabled={!route.sufficientBalance} onClick={()=>setSelectedRoute(route)} aria-pressed={selectedRoute?.id===route.id}><div><strong>{route.name}</strong><span>{route.railType} · {route.eta}</span></div><div><strong>{route.fee.toFixed(2)} {route.currency}</strong><span>{route.sufficientBalance?"Eligible":"Insufficient balance"}</span></div></button>)}</div></section>}{selectedRoute&&<section className="preview"><p className="label">04 · CONFIRM</p><h2>Review before funds are held.</h2><p>Send <strong>{amount} {currency}</strong> to <strong>{recipient?.display_name??"the verified recipient"}</strong> using <strong>{selectedRoute.name}</strong>.</p><p>Fee: {selectedRoute.fee.toFixed(2)} {selectedRoute.currency} · ETA: {selectedRoute.eta}</p><button onClick={authorize} disabled={busy||authorized}>{authorized?"Funds authorized":"Authorize and hold funds"}</button>{authorized&&<p className="session-message">Authorized successfully. Funds are held by the accounting layer. Settlement has NOT started.</p>}</section>}{message&&<p className="session-message" role="status">{message}</p>}<footer>Shadecode Money · Transfer authorization · Settlement disabled</footer></main>}
