"use client";

import { useState } from "react";
import { createClient } from "../../lib/supabase";
import { getRouteQuote, type RouteQuote } from "./quote";

type Recipient = { user_id: string; display_name: string | null; country_code: string | null };
function normalizePhone(value: string) { return value.trim().replace(/[\s()-]/g, ""); }
function nonce() { return `${crypto.randomUUID()}-${Date.now()}`; }

export default function SendPage() {
  const [phone, setPhone] = useState(""); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD");
  const [recipient, setRecipient] = useState<Recipient | null>(null); const [routes, setRoutes] = useState<RouteQuote[]>([]); const [selectedRoute, setSelectedRoute] = useState<RouteQuote | null>(null);
  const [accountId, setAccountId] = useState<string | null>(null); const [authorized, setAuthorized] = useState(false); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);

  async function findRecipient() { setBusy(true); setMessage(null); setRecipient(null); setRoutes([]); setSelectedRoute(null); setAuthorized(false); const normalized=normalizePhone(phone); if(!/^\+[1-9][0-9]{6,14}$/.test(normalized)){setMessage("Enter a valid international phone number.");setBusy(false);return;} const supabase=createClient(); const {data,error}=await supabase.rpc("lookup_money_recipient_by_phone",{p_phone_e164:normalized}); setBusy(false); if(error){setMessage(error.message);return;} const match=Array.isArray(data)?data[0]:data;if(!match){setMessage("No verified Shadecode Money recipient was found.");return;}setRecipient(match as Recipient); }

  async function quote(){setMessage(null);setRoutes([]);setSelectedRoute(null);setAuthorized(false);const numeric=Number(amount);if(!recipient)return setMessage("Find and review the recipient first.");if(!Number.isFinite(numeric)||numeric<=0)return setMessage("Enter a valid positive amount.");setBusy(true);try{const result=await getRouteQuote(numeric,currency,recipient.country_code??"");setRoutes(result.routes);if(!result.routes.length)setMessage("No eligible money rail is configured for this currency.");}catch(error){setMessage(error instanceof Error?error.message:"Route quote failed.");}finally{setBusy(false);}}

  async function authorize(){if(!recipient||!selectedRoute)return;setBusy(true);setMessage(null);try{const supabase=createClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user){setMessage("Sign in to authorize a transfer.");return;}const {data:accounts,error}=await supabase.from("money_accounts").select("id,currency").eq("owner_id",auth.user.id).eq("currency",currency).order("created_at",{ascending:true}).limit(1);if(error)throw error;const account=accounts?.[0];if(!account){setMessage(`No ${currency} account is available.`);return;}setAccountId(account.id);const amountMinor=Math.round(Number(amount)*100);const {data,error:fnError}=await supabase.functions.invoke("money-authorize-transfer-v2",{body:{accountId:account.id,currency,amountMinor,recipientPhone:normalizePhone(phone),idempotencyKey:nonce()}});if(fnError)throw fnError;if(data?.error)throw new Error(data.error);setAuthorized(true);}catch(error){setMessage(error instanceof Error?error.message:"Transfer authorization failed.");}finally{setBusy(false);}}

  return <main className="shell"><nav className="nav"><div className="brand"><span className="brand-mark">S</span><span>Shadecode</span></div><a href="/wallet">← Wallet</a></nav><section className="hero"><p className="eyebrow">SHADECODE · SEND</p><h1>Prepare a transfer.</h1><p className="subhead">Recipient, route, balance and authorization are checked before settlement can begin.</p></section>
    <section className="preview"><p className="label">01 · RECIPIENT</p><div className="recipient-form"><input inputMode="tel" placeholder="Recipient +263771234567" value={phone} onChange={e=>setPhone(e.target.value)}/><button onClick={findRecipient} disabled={busy}>{busy?"Looking up…":"Find recipient"}</button></div>{recipient&&<div className="recipient-result"><strong>{recipient.display_name??"Shadecode Money user"}</strong><span>{recipient.country_code??""}</span><p>Verified recipient identity found.</p></div>}</section>
    <section className="preview"><p className="label">02 · AMOUNT</p><div className="recipient-form"><input inputMode="decimal" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>ZAR</option><option>ZWG</option><option>GBP</option><option>EUR</option></select></div><button onClick={quote} disabled={!recipient||!amount||busy}>{busy?"Quoting…":"Get route options"}</button></section>
    {routes.length>0&&<section className="preview"><p className="label">03 · ROUTE</p><h2>Choose an eligible route.</h2><div className="route-list">{routes.map(route=><button className="transaction-row" key={route.id} disabled={!route.sufficientBalance} onClick={()=>setSelectedRoute(route)} aria-pressed={selectedRoute?.id===route.id}><div><strong>{route.name}</strong><span>{route.railType} · {route.eta}</span></div><div><strong>{route.fee.toFixed(2)} {route.currency}</strong><span>{route.sufficientBalance?"Eligible":"Insufficient balance"}</span></div></button>)}</div></section>}
    {selectedRoute&&<section className="preview"><p className="label">04 · CONFIRM</p><h2>Review before funds are held.</h2><p>Send <strong>{amount} {currency}</strong> to <strong>{recipient?.display_name??"the verified recipient"}</strong> using <strong>{selectedRoute.name}</strong>.</p><p>Fee: {selectedRoute.fee.toFixed(2)} {currency} · ETA: {selectedRoute.eta}</p><button onClick={authorize} disabled={busy||authorized}>{authorized?"Funds authorized":"Authorize and hold funds"}</button>{authorized&&<p className="session-message">Authorized successfully. Funds are held by the accounting layer. Settlement has NOT started.</p>}</section>}
    {message&&<p className="session-message" role="status">{message}</p>}<footer>Shadecode · Transfer authorization · Settlement disabled</footer></main>;
}
